language: scala
jdk: oraclejdk9
script: sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues scalafmt::test test:scalafmt::test sbt:scalafmt::test test

scala:
   - 2.10.7
   - 2.11.12
   - 2.12.4
   - 2.13.0-M2

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
