addSbtPlugin("org.scala-sbt"  % "sbt-houserules"  % "0.3.9")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"    % "2.0.3")
addSbtPlugin("org.scala-sbt"  % "sbt-contraband"  % "0.4.4")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"   % "0.9.0")
addSbtPlugin("com.lightbend"  % "sbt-whitesource" % "0.1.16")
addSbtPlugin("de.heikoseeberger" % "sbt-header" % "5.2.0")
